version: "3.8"

services:
  backend:
    build: ./backend
    container_name: reconciliation_backend
    restart: always
    volumes:
      - backend_data:/app
      # Mount .env if you want to use local .env
      - ./backend/.env:/app/.env
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/financial_db
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: reconciliation_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=financial_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: reconciliation_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  backend_data:
  postgres_data:
